source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'PDFUtilities_Example' do
  pod 'PDFUtilities', :path => '../'

  target 'PDFUtilities_Tests' do
    inherit! :search_paths

    
  end
end
